### ISSUE TITLE
Initialize backend project

### ISSUE THREAD

**Issue by anthonkendel** [anthonkendel/drinkin.games#5]

**Comment by prattheev** [comment]
@anthonkendel What do you wish to use for the backend?

And I would like to recommend a better project structure for your project. The current structure doesn't look compelling.

**Comment by anthonkendel** [comment]
@prattheev Initial plan was to use nodejs with express and mongodb. But nothing is set in stone.

Could you elaborate on the project structure part and do you have any recommendations for improvements?
